export const data = [
  {
    Game: "Blast Corps",
    Price: 29.95,
    GameLink: null,
    Year: 1997,
    Dev: "Rare",
    DevLink: "https://en.wikipedia.org/wiki/Rare_(company)",
    Publisher: "Nintendo",
    PublisherLink: "https://en.wikipedia.org/wiki/Nintendo",
    Platform: "the Nintendo 64",
    PlatformLink: "https://en.wikipedia.org/wiki/Nintendo_64",
    Genre: "Action/Strategy",
  },
  {
    Game: "Castlevania",
    Price: 49.99,
    GameLink: null,
    Year: 1999,
    Dev: "KCEK",
    DevLink: "https://en.wikipedia.org/wiki/Konami#Former_subsidiaries",
    Publisher: "Konami",
    PublisherLink: "https://en.wikipedia.org/wiki/Konami",
    Platform: "the Nintendo 64",
    PlatformLink: "https://en.wikipedia.org/wiki/Nintendo_64",
    Genre: "Action/Adventure",
  },
  {
    Game: "Goldeneye 007",
    Price: 49.99,
    GameLink: "https://en.wikipedia.org/wiki/GoldenEye_007_(1997_video_game)",
    Year: 1997,
    Dev: "Rare",
    DevLink: "https://en.wikipedia.org/wiki/Rare_(company)",
    Publisher: "Nintendo",
    PublisherLink: "https://en.wikipedia.org/wiki/Nintendo",
    Platform: "the Nintendo 64",
    PlatformLink: "https://en.wikipedia.org/wiki/Nintendo_64",
    Genre: "Action/First-Person Shooter",
  },
  {
    Game: "Doom 64",
    Price: 34.99,
    GameLink: "https://en.wikipedia.org/wiki/Doom_64",
    Year: 1997,
    Dev: "Midway Studios - San Diego",
    DevLink: "https://en.wikipedia.org/wiki/Midway_Games#Sold",
    Publisher: "Midway Home EntertainmentNA - GamebankJP - GT InteractivePAL",
    PublisherLink: null,
    Platform: "the Nintendo 64",
    PlatformLink: "https://en.wikipedia.org/wiki/Nintendo_64",
    Genre: "Action/First-Person Shooter",
  },
  {
    Game: "Mischief Makers",
    Price: 39.99,
    GameLink: null,
    Year: 1997,
    Dev: "Treasure",
    DevLink: "https://en.wikipedia.org/wiki/Treasure_(company)",
    Publisher: "EnixJP - NintendoNA/PAL",
    PublisherLink: null,
    Platform: "the Nintendo 64",
    PlatformLink: "https://en.wikipedia.org/wiki/Nintendo_64",
    Genre: "Action/2D Platformer",
  },
  {
    Game: "Turok: Dinosaur Hunter",
    Price: 39.99,
    GameLink: null,
    Year: 1997,
    Dev: "Iguana Entertainment",
    DevLink: "https://en.wikipedia.org/wiki/Acclaim_Studios_Austin",
    Publisher: "Acclaim Entertainment - Acclaim JapanJP",
    PublisherLink: null,
    Platform: "the Nintendo 64",
    PlatformLink: "https://en.wikipedia.org/wiki/Nintendo_64",
    Genre: "Action/First-Person Shooter",
  },
  {
    Game: "Mortal Kombat Mythologies: Sub-Zero",
    Price: 39.99,
    GameLink:
      "https://en.wikipedia.org/wiki/Mortal_Kombat_Mythologies:_Sub-Zero",
    Year: 1997,
    Dev: "Avalanche Software",
    DevLink: "https://en.wikipedia.org/wiki/Avalanche_Software",
    Publisher: "Midway Home EntertainmentNA - GT InteractivePAL",
    PublisherLink: null,
    Platform: "the Nintendo 64",
    PlatformLink: "https://en.wikipedia.org/wiki/Nintendo_64",
    Genre: "Action/Beat 'em up",
  },
  {
    Game: "International Superstar Soccer '98",
    Price: 29.99,
    GameLink: null,
    Year: 1998,
    Dev: "KCEO",
    DevLink: "https://en.wikipedia.org/wiki/Konami#Former_subsidiaries",
    Publisher: "Konami",
    PublisherLink: "https://en.wikipedia.org/wiki/Konami",
    Platform: "the Nintendo 64",
    PlatformLink: "https://en.wikipedia.org/wiki/Nintendo_64",
    Genre: "Sports/Soccer",
  },
  {
    Game: "Top Gear Overdrive",
    Price: 39.99,
    GameLink: "https://en.wikipedia.org/wiki/Top_Gear_Overdrive",
    Year: 1999,
    Dev: "Snowblind Studios",
    DevLink: "https://en.wikipedia.org/wiki/Snowblind_Studios",
    Publisher: "Kemco",
    PublisherLink: "https://en.wikipedia.org/wiki/Kemco",
    Platform: "the Nintendo 64",
    PlatformLink: "https://en.wikipedia.org/wiki/Nintendo_64",
    Genre: "Racing/Automobile",
  },
  {
    Game: "The Legend of Zelda: Ocarina of Time",
    Price: 49.99,
    GameLink:
      "https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Ocarina_of_Time",
    Year: 1998,
    Dev: "Nintendo EAD",
    DevLink:
      "https://en.wikipedia.org/wiki/Nintendo_Entertainment_Analysis_%26_Development",
    Publisher: "Nintendo",
    PublisherLink: "https://en.wikipedia.org/wiki/Nintendo",
    Platform: "the Nintendo 64",
    PlatformLink: "https://en.wikipedia.org/wiki/Nintendo_64",
    Genre: "Action/Adventure",
  },
];
